### ISSUE TITLE
Indexing stuck 

### ISSUE THREAD

**Issue by lintangtimur** [skylot/jadx#393]
when i searching some text code,
program loading decompiling and then indexing and stuck 63%

**Comment by jpstotz** [comment]
Please check the CPU usage. If it is very high (multiple cores with 100%) it may be a memory problem (the CPU usage is because of the garbage collector trying to free memory again and again). 

If the CPU usage is not very high you should post a link to the apk of the app your are trying to load.

**Comment by lintangtimur** [comment]
@jpstotz yes 100%

**Comment by lintangtimur** [comment]
How to assign more ram to jadx?

**Comment by idb-** [comment]
I am having this same issue when trying to decompile the latest Uber apk. Have assigned more ram to Jadx. No difference.

**Comment by jpstotz** [comment]
@idb- Try the latest unstable build: https://bintray.com/skylot/jadx/unstable/_latestVersion#files

Several problems with index generation have been fixed since 0.8.0.

**Comment by idb-** [comment]
Still occurring in the latest unstable build. Actually went unresponsive during the decompilation process and never even made it to indexing.

**Comment by jpstotz** [comment]
Latest unstable build of Jadx runs fine for the app [com.ubercab](https://play.google.com/store/apps/details?id=com.ubercab). I can not verify your problems.  

Make sure Jadx has more than 4GB as maximum heap size set. The maximum heap size is visible in the memory bar at the bottom of the Jadx window in the unstable builds. For the ueber app I would recommend at least 6GB max heap size.

**Comment by asashour** [comment]
Any sample APK, to reproduce the issue please?

**Comment by jpstotz** [comment]
This issue should be fixed by PR #433.

**Comment by mkabirWM** [comment]
> 
Can you please me the way to allocate more Ram to Jadx?

**Comment by mkabirWM** [comment]
> Then Jadx is running out of memory and you have to assign more RAM to Jadx: https://github.com/skylot/jadx#Troubleshooting

Already tried this, but didn't work for Amazon Alexa apk. Can you please give me any idea how to solve this?

**Comment by skylot** [comment]
@mkabirWM well, your sample works fine for me with 4G of memory, just in case make sure you use `DISK` code cache mode.

**Comment by mkabirWM** [comment]
![image](https://user-images.githubusercontent.com/125955668/226443413-1d6cc4b2-8c4c-419a-98fa-8b275f16835a.png)







> @mkabirWM check https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A#assign-more-ram-eg-6gb-to-jadx

Well, these are the steps I have done to solve the issue but still, it persists. Can you please tell if I have done anything wrong in the steps?

1. Create jadx-gui.l4j.ini file in the same directory of the jadx-ui.exe.
![image](https://user-images.githubusercontent.com/125955668/226443819-3312d9b5-b7c4-426e-9692-09452f1f2875.png)

2. Contents of that file is: 
![image](https://user-images.githubusercontent.com/125955668/226444074-0ecc4e1d-1e50-44d5-bd51-5cc1599b8dde.png)

Then, I restarted my jadx-ui.exe. Stil I can see the Ram is showing 4 gb. 

![image](https://user-images.githubusercontent.com/125955668/226444271-e5948db1-4429-43bc-a8a2-3246c7bd1ff0.png)


**note:** 
Here is the Disk code cache settings: 
![image](https://user-images.githubusercontent.com/125955668/226444508-4ead1cb6-c9e0-4854-80dd-e5d1b1697989.png)


and my Laptop has 16 Gb of RAM.

**Comment by skylot** [comment]
>  Stil I can see the Ram is showing 4 gb.

Rename `jadx-gui.l4j.ini` file to `jadx-gui-1.4.6-no-jre-win.l4j.ini`

**Comment by skylot** [comment]
It is weird that memory setting still not apply, I will try to check that.

Also, not sure, maybe your java version is old, try a [`jadx-gui-1.4.6-with-jre-win.zip`](https://github.com/skylot/jadx/releases/download/v1.4.6/jadx-gui-1.4.6-with-jre-win.zip) bundle, hope it will help.

**Comment by mkabirWM** [comment]
> It is weird that memory setting still not apply, I will try to check that.
> 
> Also, not sure, maybe your java version is old, try a [`jadx-gui-1.4.6-with-jre-win.zip`](https://github.com/skylot/jadx/releases/download/v1.4.6/jadx-gui-1.4.6-with-jre-win.zip) bundle, hope it will help.

Resolved the issue. There was an environmental variable named "_JAVA_OPTIONS" in my settings which was set to 4 GB. I did not remove that one. This was causing the issue. Thank you for the help.
