### ISSUE TITLE
[core] Use of static fields instead of enum constants #2

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#926]
Class `com.google.zxing.qrcode.decoder.ErrorCorrectionLevel`
```java
package com.google.zxing.qrcode.decoder;

/* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
public final class ErrorCorrectionLevel extends java.lang.Enum<com.google.zxing.qrcode.decoder.ErrorCorrectionLevel> {
    private static final /* synthetic */ com.google.zxing.qrcode.decoder.ErrorCorrectionLevel[] $VALUES;
    private static final com.google.zxing.qrcode.decoder.ErrorCorrectionLevel[] FOR_BITS;

    /* renamed from: H */
    public static final com.google.zxing.qrcode.decoder.ErrorCorrectionLevel f976H = new com.google.zxing.qrcode.decoder.ErrorCorrectionLevel("H", 3, 2);

    /* renamed from: L */
    public static final com.google.zxing.qrcode.decoder.ErrorCorrectionLevel f977L = new com.google.zxing.qrcode.decoder.ErrorCorrectionLevel("L", 0, 1);
```

APK: https://drive.google.com/file/d/1ICfL4A22K-KhVkw5RwvWdLJA8111iYvG/view?usp=sharing

**Comment by sergey-wowwow** [comment]
Hey @skylot!
I see a lot of such bugs. May you please check this one?

**Comment by skylot** [comment]
@sergey-wowwow this case fixed. But notice that other cases may have a different pattern, and not yet covered.

**Comment by sergey-wowwow** [comment]
Thanks @skylot! But there is one more issue

APK: https://drive.google.com/file/d/1XlE3s-W5H5N5RfjP_1wGtdBwk6ycYGD8/view?usp=sharing

Class `androidx.constraintlayout.solver.SolverVariable`
```java
    /* renamed from: androidx.constraintlayout.solver.SolverVariable$1 */
    static /* synthetic */ class C01871 {
        static final /* synthetic */ int[] $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type = new int[androidx.constraintlayout.solver.SolverVariable.Type.values().length];

        /* JADX WARNING: Can't wrap try/catch for region: R(12:0|1|2|3|4|5|6|7|8|9|10|12) */
        /* JADX WARNING: Code restructure failed: missing block: B:13:?, code lost:
            return;
         */
        /* JADX WARNING: Failed to process nested try/catch */
        /* JADX WARNING: Missing exception handler attribute for start block: B:3:0x0014 */
        /* JADX WARNING: Missing exception handler attribute for start block: B:5:0x001f */
        /* JADX WARNING: Missing exception handler attribute for start block: B:7:0x002a */
        /* JADX WARNING: Missing exception handler attribute for start block: B:9:0x0035 */
        static {
            $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[androidx.constraintlayout.solver.SolverVariable.Type.UNRESTRICTED.ordinal()] = 1;
            $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[androidx.constraintlayout.solver.SolverVariable.Type.CONSTANT.ordinal()] = 2;
            $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[androidx.constraintlayout.solver.SolverVariable.Type.SLACK.ordinal()] = 3;
            $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[androidx.constraintlayout.solver.SolverVariable.Type.ERROR.ordinal()] = 4;
            $SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[androidx.constraintlayout.solver.SolverVariable.Type.UNKNOWN.ordinal()] = 5;
        }
    }
```
```java
        int i = androidx.constraintlayout.solver.SolverVariable.C01871.$SwitchMap$androidx$constraintlayout$solver$SolverVariable$Type[type.ordinal()];
        if (i == 1) {
```

Can those enum constant be also addressed by their names, but not synthetic ints?

**Comment by skylot** [comment]
>  Can those enum constant be also addressed by their names, but not synthetic ints?

Sure, usually such arrays used to remap keys to made switch compact (`packed-switch` insn) and jadx can handle such cases.
But here switch was replaced by `if-else` chain (`d8` do it for small switches) so jadx missed that case.
I will try to fix it. And thanks for the sample! :smiley:

**Comment by bagipro** [comment]
The issue is fixed

**Comment by enriquejr99** [comment]
The following enum pattern is not covered.
Class: `p000X.EnumC10380bi (X.0bi)`
APK: [Instagram v174.0.0.31.132](https://m.apkpure.com/es/instagram/com.instagram.android/download/272382110-APK-d48d4d6c73839e8456819c608a6d1c4a?from=variants%2Fversion)

```
package p000X;

import java.util.Collections;
import java.util.Map;

/* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
/* renamed from: X.0bi  reason: invalid class name and case insensitive filesystem */
public final class EnumC10380bi extends Enum {
    public static final Map A01 = Collections.unmodifiableMap(new C10370bh());
    public static final /* synthetic */ EnumC10380bi[] A02;
    public static final EnumC10380bi A03;
    public static final EnumC10380bi A04;
    public static final EnumC10380bi A05;
    public static final EnumC10380bi A06;
    public static final EnumC10380bi A07;
    public static final EnumC10380bi A08;
    public static final EnumC10380bi A09;
    public static final EnumC10380bi A0A;
    public static final EnumC10380bi A0B;
    public static final EnumC10380bi A0C;
    public final int A00;

    static {
        EnumC10380bi r26 = new EnumC10380bi("CONNECT", 0, 1);
        A04 = r26;
        EnumC10380bi r25 = new EnumC10380bi("CONNACK", 1, 2);
        A03 = r25;
        EnumC10380bi r24 = new EnumC10380bi("PUBLISH", 2, 3);
        A08 = r24;
        EnumC10380bi r23 = new EnumC10380bi("PUBACK", 3, 4);
        A07 = r23;
        EnumC10380bi r22 = new EnumC10380bi("PUBREC", 4, 5);
        EnumC10380bi r21 = new EnumC10380bi("PUBREL", 5, 6);
        EnumC10380bi r20 = new EnumC10380bi("PUBCOMP", 6, 7);
        EnumC10380bi r19 = new EnumC10380bi("SUBSCRIBE", 7, 8);
        A0A = r19;
        EnumC10380bi r18 = new EnumC10380bi("SUBACK", 8, 9);
        A09 = r18;
        EnumC10380bi r17 = new EnumC10380bi("UNSUBSCRIBE", 9, 10);
        A0C = r17;
        EnumC10380bi r5 = new EnumC10380bi("UNSUBACK", 10, 11);
        A0B = r5;
        EnumC10380bi r3 = new EnumC10380bi("PINGREQ", 11, 12);
        A05 = r3;
        EnumC10380bi r1 = new EnumC10380bi("PINGRESP", 12, 13);
        A06 = r1;
        A02 = new EnumC10380bi[]{r26, r25, r24, r23, r22, r21, r20, r19, r18, r17, r5, r3, r1, new EnumC10380bi("DISCONNECT", 13, 14)};
    }

    public static EnumC10380bi valueOf(String str) {
        return (EnumC10380bi) Enum.valueOf(EnumC10380bi.class, str);
    }

    public static EnumC10380bi[] values() {
        return (EnumC10380bi[]) A02.clone();
    }

    public EnumC10380bi(String str, int i, int i2) {
        this.A00 = i2;
    }
}
```

**Comment by skylot** [comment]
@enriquejr99 thanks for the report. I made a fix for your case.
Issue here caused by several removed fields, so corresponding enum values are not saved and can't be used, but still appear in values arrays. For such values I made fake fields and add comment `/* Fake field, exist only in values array */` so enum now looks like:
```java
public enum EnumC07570bi {
    CONNECT(1),
    CONNACK(2),
    PUBLISH(3),
    PUBACK(4),
    /* Fake field, exist only in values array */
    PUBREC(5),
    /* Fake field, exist only in values array */
    PUBREL(6),
    /* Fake field, exist only in values array */
    PUBCOMP(7),
    SUBSCRIBE(8),
    SUBACK(9),
    UNSUBSCRIBE(10),
    UNSUBACK(11),
    PINGREQ(12),
    PINGRESP(13),
    /* Fake field, exist only in values array */
    DISCONNECT(14);
    
    public static final Map A01 = Collections.unmodifiableMap(new C07560bh());
    public final int A00;

    /* access modifiers changed from: public */
    EnumC07570bi(int i) {
        this.A00 = i;
    }
}
```

**Comment by enriquejr99** [comment]
Great! Thanks.

**Comment by baijialeicu** [comment]
baccarat【   www.baijiale.icu   】Is a very popular gambling game, its rules are simple but requires a certain strategy to get the best winning rate. We will introduce several common baccarat playing methods to help players get a higher winning rate in the game.

**Comment by bongdaworld** [comment]
Football【   www.bongdaworld.com   】 is a popular sport in Vietnam and is loved by many people. Local and national football tournaments such as the V-League, National Cup, and the AFC U23 Championship have attracted the interest of millions of fans. In this article, I will mention some highlights of football in Vietnam and the outstanding players of the national team.

**Comment by baijialeicu** [comment]
Gaming is a popular sport in Vietnam that is enjoyed by many people. Local and national football events such as the V-League, National Cup, AFC U23 Championship attract the interest of millions of football fans. With one of these sites below, there's always a game for everyone!


https://www.speakby.com
https://www.or-gal.com
https://www.jobstud.com
https://www.dialoe.com
https://www.shidorr.com
https://www.disquse.com
https://www.yomlm.com
https://www.igwmi.com
https://www.paudu.com
https://www.elvisyu.com
https://www.metrah.com
https://www.erace1.com
https://www.pcoex.com
https://www.natwil.com
https://www.blipcat.com
https://www.mws1970.com
https://www.qwelse.com
https://www.j4store.com
https://www.psmet.com
https://www.hcctn.com
https://www.uaydin.com
https://www.club6e.com
https://www.600bst.com
https://www.pushcg.com
https://www.tomios.com
https://www.3gsurf.com
https://www.vversus.com
https://www.uireny.com
https://www.marsgt.com
https://www.nbortz.com
https://www.giacngu.com
https://www.myqeye.com
https://www.untenu.com
https://www.sallapp.com
https://www.karpub.com
https://www.alrait.com
https://www.dmegypt.com
https://www.nilepal.com
https://www.mmmani.com
https://www.zettajs.com
https://www.pty2060.com
https://www.paraoh.com
https://www.jpacu.com
https://www.mls-oil.com
https://www.ejelome.com
https://www.wasausa.com
https://www.vdsipl.com
https://www.npzco.com
https://www.skispat.com
https://www.itomono.com
https://www.eleank.com
https://www.sshalin.com
https://www.ppk-69.com
https://www.novorss.com
https://www.ubuggin.com
https://www.zeppidy.com
https://www.nybshop.com
https://www.seo4biz.com
https://www.alnobla.com
https://www.huhchat.com
https://www.ugomove.com
https://www.imgplz.com
https://www.peridyn.com
https://www.mfonido.com
https://www.sasqweb.com
https://www.mmanewz.com
https://www.hb4939.com
https://www.fgugak.com
https://www.jubalam.com
https://www.pozzr.com
https://www.dmailme.com
https://www.socbeez.com
https://www.doajax.com
https://www.jmlotus.com
https://www.rdtail.com
https://www.fts21.com
https://www.m4blog.com
https://www.suipis.com
https://www.gifloop.com
https://www.zzwst.com
https://www.pideley.com
https://www.kdchild.com
https://www.neneva.com
https://www.pdxkcm.com
https://www.tubes-x.com
https://www.tignow.com
https://www.olisoun.com
https://www.i-ctec.com
https://www.tatepos.com
https://www.ws-ab.com
https://www.egezltd.com
https://www.safkati.com
https://www.luco65.com
https://www.e-istqb.com
https://www.hwevent.com
www.star24tvbd.com
www.sanatandharmik.com
www.charterkala.com
www.hanwonsam.com
www.ledpiramida.com
www.remoper.com
www.granground.com
www.longavita-ural.com
www.cps-prog.com
www.kleosun.com
www.weaspace.com
www.extra-fruit.com
www.dalalhussein.com
www.diaocdaiphugia.com
www.viktoriasad.com
www.taewon-ind.com
www.krabibattery.com
www.kushiro-bankin.com
www.ik-sever.com
www.nitka-bus.com
www.alejandrovrojas.com
www.carmen-becerra.com
www.wisetresidence.com
www.distrito113.com
www.barbusforum.com
www.g-days-room.com
www.bazooka3.com
www.donghoctime.com
www.tanabiotech.com
www.ns-okinawa.com
www.tokuoffclub.com
www.miveban.com
www.kumchev.com
www.suakhoa-danang.com
www.subculturework.com
www.siamhypezone.com
